import { Lexend, Montserrat } from 'next/font/google';
import localFont from "next/font/local";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css';
import './sass/helper/base.scss';
import './sass/helper/helper.scss';
import './sass/helper/reset.scss';
import Header from "./components/header";
import Footer from './components/footer';
import 'animate.css';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

 const lexend = Lexend({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-lexend'

})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" /></head>
      <body id='pb_scroll' className={` ${lexend.variable} ${geistSans.variable} ${geistMono.variable} ${montserrat.className} `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
